// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductInput struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type DeleteProductResponse struct {
	DeleteProductID string `json:"deleteProductId"`
}

type Product struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type UpdateProductInput struct {
	Title       *string  `json:"title,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
}
